version: '3'

services:
  redis-cluster:
    image: makeomatic/redis-cluster:3.2.9
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
    environment:
      - IP=127.0.0.1

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
